kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-pangu
  labels:
    name: pv-pangu
spec:
  storageClassName: nfs-pangu
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  nfs:
    server: 192.168.100.81
    path: /data/volumes
  capacity:
    storage: 2Gi
