apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: ns-pangu
spec:
  ports:
  - port: 7761
    protocol: TCP
    targetPort: 7761
  type: NodePort
  selector:
    environment: dev
    app: eureka-server
