---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
  namespace: ns-pangu
spec:
  selector:
    app: eureka-server
  ports:
    - name: web
      port: 80
      targetPort: 7761

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: eureka-ingress
  namespace: ns-pangu
spec:
  rules:
  - host: eureka.scnebula.com
    http:
      paths:
      - path: /
        backend:
          serviceName: eureka-server-service
          servicePort: web
